// Code generated by "stringer -type=DataMode"; DO NOT EDIT.

package binary

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataModeActive-1]
	_ = x[DataModePassive-2]
}

const _DataMode_name = "DataModeActiveDataModePassive"

var _DataMode_index = [...]uint8{0, 14, 29}

func (i DataMode) String() string {
	i -= 1
	if i < 0 || i >= DataMode(len(_DataMode_index)-1) {
		return "DataMode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DataMode_name[_DataMode_index[i]:_DataMode_index[i+1]]
}
