// Code generated by "stringer -type=OpcodeFC"; DO NOT EDIT.

package opcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpcodeFCI32TruncSatF32S-0]
	_ = x[OpcodeFCI32TruncSatF32U-1]
	_ = x[OpcodeFCI32TruncSatF64S-2]
	_ = x[OpcodeFCI32TruncSatF64U-3]
	_ = x[OpcodeFCI64TruncSatF32S-4]
	_ = x[OpcodeFCI64TruncSatF32U-5]
	_ = x[OpcodeFCI64TruncSatF64S-6]
	_ = x[OpcodeFCI64TruncSatF64U-7]
	_ = x[OpcodeFCMemoryInit-8]
	_ = x[OpcodeFCDataDrop-9]
	_ = x[OpcodeFCMemoryCopy-10]
	_ = x[OpcodeFCMemoryFill-11]
	_ = x[OpcodeFCTableInit-12]
	_ = x[OpcodeFCElemDrop-13]
	_ = x[OpcodeFCTableCopy-14]
	_ = x[OpcodeFCTableGrow-15]
	_ = x[OpcodeFCTableSize-16]
	_ = x[OpcodeFCTableFill-17]
}

const _OpcodeFC_name = "OpcodeFCI32TruncSatF32SOpcodeFCI32TruncSatF32UOpcodeFCI32TruncSatF64SOpcodeFCI32TruncSatF64UOpcodeFCI64TruncSatF32SOpcodeFCI64TruncSatF32UOpcodeFCI64TruncSatF64SOpcodeFCI64TruncSatF64UOpcodeFCMemoryInitOpcodeFCDataDropOpcodeFCMemoryCopyOpcodeFCMemoryFillOpcodeFCTableInitOpcodeFCElemDropOpcodeFCTableCopyOpcodeFCTableGrowOpcodeFCTableSizeOpcodeFCTableFill"

var _OpcodeFC_index = [...]uint16{0, 23, 46, 69, 92, 115, 138, 161, 184, 202, 218, 236, 254, 271, 287, 304, 321, 338, 355}

func (i OpcodeFC) String() string {
	if i >= OpcodeFC(len(_OpcodeFC_index)-1) {
		return "OpcodeFC(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpcodeFC_name[_OpcodeFC_index[i]:_OpcodeFC_index[i+1]]
}
